apiVersion: v1
kind: PersistentVolume
metadata:
  name: student-app-pv
spec:
  capacity:
    storage: 8Gi
  volumeMode: Filesystem
  accessModes: 
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  csi:
    driver: ebs.csi.aws.com
    volumeHandle: vol-0cadc0868fb9c5749
    fsType: ext4
    volumeAttributes: 
      storage.kubernetes.io/csiProvisionerIdentity: static
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - {key: topology.kubernetes.io/zone, operator: In, values: ["us-east-2a"]}

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: student-app-pvc
spec:
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  
